[project]
name = "14-marimo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bauplan>=0.0.3a395",
    "marimo==0.13.14",
    "polars>=1.30.0",
]
