service: hello-data-product-lambda

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  memorySize: 3008
  timeout: 600
  ecr:
    images:
      dataproductimage:
        path: ./
        platform: linux/amd64
  environment:
    HOME: /tmp

  # Define IAM Role statements so the Lambda can access your S3 bucket
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::hello-data-products-with-bauplan
        - arn:aws:s3:::hello-data-products-with-bauplan/*

functions:
  dataProductFunction:
    ephemeralStorageSize: 1024
    environment:
      bauplan_key: ${env:BPLN_KEY}
      bauplan_user: ${env:BPLN_USER}
    image:
      name: dataproductimage
    events:
      - schedule: rate(30 minutes)

